[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::sqlalchemy.exc.MovedIn20Warning
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore:.*dict method is deprecated.*
    ignore:.*The `dict` method is deprecated.*
    ignore:.*utcnow.*
    ignore:.*datetime.datetime.utcnow.*
    ignore:.*starlette.testclient.*
    ignore:.*StarletteDeprecationWarning.*
